
@host = http://localhost:20109


###
PATCH  {{host}}/notes/renameNote HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNeW5rYSIsImlhdCI6MTc2OTQ1Mjg4NCwiZXhwIjoxNzY5NDg4ODg0fQ.7DCmsaP9cbc8JQKUP32mNSfIurcZmldTevhBP8Xjlmw

{
"id":18,
"newName":"Elo"
}



###
GET {{host}}/notes/getNoteSuggestedTags HTTP/1.1
content-type: application/json

{
"path": "/"
}


###
POST {{host}}/subjects/addSubject HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJteW5rYSIsImlhdCI6MTc3MTYwNzEwMCwiZXhwIjoxNzcxNjQzMTAwfQ.PusU2vfwYdR8JdiM7X6d_WiqfqukaiLMrspeHxu4Kp8

{
"path": "/test/test2/test3",
"name": "testowego"
}


