@host = http://localhost:20109

###
POST {{host}}/union/checkEmail HTTP/1.1
content-type: application/json

mynka3@wp.pl

###
POST {{host}}/union/signUp HTTP/1.1
content-type: application/json

{
"username":"Mynka3",
"email":"flisikowska.emilia@gmail.com",
"password":"Mynka98!",
"confirmPassword":"Mynka98!"
}

###
POST {{host}}/union/checkUsername HTTP/1.1
content-type: application/json

Mynka6

###
POST {{host}}/union/verify HTTP/1.1
content-type: application/json

{
"email":"flisikowska.emilia@gmail.com",
"token":"771994"
}

###
POST {{host}}/union/signup HTTP/1.1
content-type: application/json

{
"email":"flisikowska.emilia@gmail.com",
"token":"771994"
}

###
POST {{host}}/union/resendVerificationCode HTTP/1.1
content-type: application/json


mynka3@wp.pl

###
POST {{host}}/union/signIn HTTP/1.1
content-type: application/json

{
"login":"flisikowska.emilia@gmail.com",
"password":"Emilka123!"
}


